# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a554e7a67598e61936a01c09d9a3f5577b09038eb0543cbe35bb372d2659f5fa5a131391d47ba526269f6c8d9d91b99a0586a08a669a890fff77df2fa0ed50b4

test:
  secret_key_base: d34bdfeb52200169482dc342ab6522026822cc0462ea2c943a6d53e031350fc81f8a8414d2488b5dbba986aa434fe9fc1283bcc30b774af3ec675f89eb8738e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
